[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["src"]
skip_glob = ["src/database/models/__init__.py"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
namespace_packages = true

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-report=xml"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["*/__init__.py"]

[tool.setuptools]
packages = ["src"]

[project]
name = "zmbackup"
version = "2.0.0"
description = "A CLI tool for managing zmbackup sessions."
dependencies = [
    "click",
    "prettytable",
]

[project.scripts]
zmbackup = "cli:cli"